### ISSUE TITLE
Is there a function to build a connection string?

### ISSUE THREAD

**Issue by nagylzs** [jackc/pgconn#122]
The `pgconn.ParseConfig` function can be used to parse a connection string into `pgconn.Config`. I need the inverse of this function. I'm working with repmgr postgresql clusters, and I need to write code that monitors multiple nodes in the same cluster. Most basic functions needed are: replace host and port in a connection string.

The official documentation here https://www.postgresql.org/docs/current/libpq-connect.html#AEN39024 says that parameter values must be single quoted, and single quotes and backslash characters should be escaped with backslash. But there is much more to this. `pgconn` also considers default settings. environment variables etc. Also, values can (apparently) be encoded with urlencode (percent signs). Because of these extra features, it is not trivial to write a function that can manipulate a connection string, and correctly replace individual parameters inside of it.

I cannot simply replace the `Host` and `Port` fields in the parsed `Config` struct, it is mentioned at https://pkg.go.dev/github.com/jackc/pgconn@v1.12.1#ParseConfig that some parameters (including the host) is also used in the TLS configuration, and directly modifying fields in the parsed `Config` struct can cause unexpected connection errors.

I understand that this is a narrow use case. But it is also a feature that is strictly about manipulating connection strings. It would be logical to place it inside pgconn.

(Or maybe it is aready supported, just I don't know about it?)

**Comment by jackc** [comment]
There's no way to go from an arbitrary `Config` to a connection string. But a `Config` can give you back the connection string that was originally parsed from: https://pkg.go.dev/github.com/jackc/pgx/v4#ConnConfig.ConnString

**Comment by nagylzs** [comment]
All right, then I'll brew my own. Thank you!
