### ISSUE TITLE
Retry if error is "hostname resolving error"

### ISSUE THREAD

**Issue by nbajaj90** [jackc/pgconn#132]
https://github.com/jackc/pgconn/blob/1e1135688ea919f66b9425b5bfe06f14ef1e5285/pgconn.go#L148

In application, observing intermittent failures for "hostname resolving error" (Works most of the time but seeing intermittent failures).  Is there any way to add retries for this error? So that if the error happens for any DB call, it retries implicitly before failing with this error.

**Comment by jackc** [comment]
Sorry, there's no automatic retry logic built in. There's no one size fits all rule for automatic retries so it is extremely unlikely to ever be added either. This would need to be handled with a wrapper above pgx/pgconn.

Also, just to make sure you are aware, this is the repo for the pgconn that works with pgx v4. In pgx v5, pgconn was merged into the pgx repo.
