### ISSUE TITLE
Parsing errors expose password

### ISSUE THREAD

**Issue by 76creates** [jackc/pgconn#135]
`e.err.Error()` can contain passwords on line: https://github.com/jackc/pgconn/blob/e82f7d1fadf5970c308d0502d196783e72467178/errors.go#L102

My password contained `%S` in it, could be useful for testing.

**Comment by jackc** [comment]
The error messages are redacted on a best effort basis. See `redactPW`. However, since the connection string could not be parsed it can only be on a best effort basis.

**Comment by 76creates** [comment]
Fair enough, I will close this one, thanks!
