### ISSUE TITLE
# special symbol is not supported in URL

### ISSUE THREAD

**Issue by jabalv** [jackc/pgconn#18]
Parse function (https://golang.org/pkg/net/url/#Parse) used in:
https://github.com/jackc/pgconn/blob/32350bd1dc3288aa22f271f87065741da0a1bdb8/config.go#L350
returns broken url when special symbol '#' is used, i.e., password field.

It's broken in net/url Parse f-tion:
https://golang.org/src/net/url/url.go?s=13280:13319#L473

I tried to use: https://golang.org/pkg/net/url/#ParseRequestURI
But it supports HTTP schema only. I think net/url package should have function to support different URI schemas. Could this be something for GO team?

**Comment by jackc** [comment]
I'm not sure what the correct behavior is according to the standard.  However, it works if you URL encode the password.

https://play.golang.org/p/-QwgJ4x0WWp

**Comment by jabalv** [comment]
When URL is encoded it even works with with net/url Parse function that you use.
https://play.golang.org/p/mGxMXWo_x9N
