### ISSUE TITLE
ParseConfig can't handle empty hostnames

### ISSUE THREAD

**Issue by johanbrandhorst** [jackc/pgconn#19]
When using `pgconn.ParseConfig` on a connection string that doesn't specify a hostname, such as `postgresql://root@:5432/postgres`, `pgconn.ParseConfig` produces a config with a host of `/tmp`.

This appears to be because the default host is not overwritten, since the parsed host is not stored if it is empty: https://github.com/jackc/pgconn/blob/32350bd1dc3288aa22f271f87065741da0a1bdb8/config.go#L367.

Not sure if this is an unintentional limitation, but these hostname-less connection strings worked in older versions of `pgx` and generally works when using the Go network libraries, so it would be nice to support it.

**Comment by jackc** [comment]
I hadn't considered that possibility of an empty host. What does dial do without a host?

FWIW, the tests still pass if we changed it so I'm not not opposed to changing this -- just never have run into a url without a host.

**Comment by johanbrandhorst** [comment]
In my experience empty host resolves to `localhost`. I don't know if this is a Go peculiarity. I'd be happy to put together a PR.

**Comment by jackc** [comment]
Sounds good to me.

**Comment by johanbrandhorst** [comment]
After some testing and digging around, we found that libpq, as defined on this page: https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNECT-HOST, handles empty hosts by default to `/tmp`. It does not mention what to do when the port is valid but the hostname is empty, so it seems reasonable to keep the current behaviour and require hostnames to be provided explicitly.
