### ISSUE TITLE
CopyFrom gets stuck if NoticeResponse received during stream

### ISSUE THREAD

**Issue by rogerhub** [jackc/pgconn#21]
I noticed a bug in this code:

https://github.com/jackc/pgconn/blob/fcfd7d09a9079edbce62cf83d5d184e8b2dbc33e/pgconn.go#L1001-L1030

The signalMessage() method starts a goroutine that closes the channel when a message is received. This makes the main loop call receiveMessage to process the message. However, receiveMessage ends up getting called on every subsequent iteration, because the channel is closed from then on.

The second call to receiveMessage gets stuck, because there was only 1 message to process.

On the other hand, if there's more than one message to receive, then CopyFrom can get stuck on Write(), because the database is waiting to transmit the message (ClientWrite) and not reading more data. The current code assumes that each Write can only trigger at most 1 notice in response.

Here's my crappy attempt at a fix:

```diff
diff --git a/pgconn.go b/pgconn.go
index e3f3aaf..69ff37b 100644
--- a/pgconn.go
+++ b/pgconn.go
@@ -997,35 +997,47 @@ func (pgConn *PgConn) CopyFrom(ctx context.Context, r io.Reader, sql string) (Co
 	buf = make([]byte, 0, 65536)
 	buf = append(buf, 'd')
 	sp := len(buf)
-	var readErr error
-	signalMessageChan := pgConn.signalMessage()
-	for readErr == nil && pgErr == nil {
-		var n int
-		n, readErr = r.Read(buf[5:cap(buf)])
-		if n > 0 {
-			buf = buf[0 : n+5]
-			pgio.SetInt32(buf[sp:], int32(n+4))
+	var (
+		readErr error
+		signalMessageChan = pgConn.signalMessage()
+		copyChan = make(chan error)
+	)
+	go func() {
+		for {
+			n, err := r.Read(buf[5:cap(buf)])
+			if n > 0 {
+				buf = buf[0 : n+5]
+				pgio.SetInt32(buf[sp:], int32(n+4))
 
-			_, err = pgConn.conn.Write(buf)
+				_, err = pgConn.conn.Write(buf)
+				if err != nil {
+					pgConn.hardClose()
+					copyChan <- err
+					break
+				}
+			}
 			if err != nil {
-				pgConn.hardClose()
-				return nil, err
+				copyChan <- err
+				break
 			}
 		}
-
+	}()
+	for readErr == nil && pgErr == nil {
 		select {
+		case err := <-copyChan:
+			readErr = err
 		case <-signalMessageChan:
 			msg, err := pgConn.receiveMessage()
 			if err != nil {
 				pgConn.hardClose()
 				return nil, err
 			}
+			signalMessageChan = pgConn.signalMessage()
 
 			switch msg := msg.(type) {
 			case *pgproto3.ErrorResponse:
 				pgErr = ErrorResponseToPgError(msg)
 			}
-		default:
 		}
 	}
```

hardClose() ought to be moved out of the goroutine, but I didn't bother doing that.

Can you confirm whether this is a bug? Thanks!

**Comment by jackc** [comment]
Thanks for the detailed report.

Based on your description, the code, and the PostgreSQL docs stating that notice response is allowed during a copy it does appear to be a bug.

However, I was unable to duplicate it in a test case. I used a trigger to create a notice on insert but regardless of how many rows were written by the copy or how many or how large the notices generated by the insert were it always buffered the NoticeResponse messages until after the copy sending was complete. I tried on Linux with PostgreSQL 10 and 12 and on MacOS with PostgreSQL 12.

Anyway, I'm reasonably confident that dd53b7488d920c44204098385e460cf708626a42 should resolve the issue -- but I don't have a test case to prove it.

**Comment by rogerhub** [comment]
Ah, my bad. I should have provided a test case. I initially ran into this bug because of a trigger that sets a tsvector column. If there are long words, then postgres gives notice responses like:

```
NOTICE:  word is too long to be indexed
DETAIL:  Words longer than 2047 characters are ignored.
```

Here's a test case that just hangs (timeout) with v1.3.0 but passes with my patch:

```go
package pgconn_21_test

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"testing"

	"github.com/jackc/pgconn"
	"github.com/stretchr/testify/require"
)

func TestPgconn21(t *testing.T) {
	ctx := context.Background()
	pgConn, err := pgconn.Connect(ctx, os.Getenv("PGX_TEST_CONN_STRING"))
	require.NoError(t, err)
	defer pgConn.Close(ctx)

	_, err = pgConn.Exec(ctx, `create temporary table sentences(
		t text,
		ts tsvector
	)`).ReadAll()
	require.NoError(t, err)

	_, err = pgConn.Exec(ctx, `create function pg_temp.sentences_trigger() returns trigger as $$
	begin
	  new.ts := to_tsvector(new.t);
		return new;
	end
	$$ language plpgsql;`).ReadAll()
	require.NoError(t, err)

	_, err = pgConn.Exec(ctx, `create trigger sentences_update before insert on sentences for each row execute procedure pg_temp.sentences_trigger();`).ReadAll()
	require.NoError(t, err)

	longString := make([]byte, 10001)
	for i := range longString {
		longString[i] = 'x'
	}

	buf := &bytes.Buffer{}
	for i := 0; i < 1000; i++ {
		buf.Write([]byte(fmt.Sprintf("%s\n", string(longString))))
	}

	_, err = pgConn.CopyFrom(ctx, buf, "COPY sentences(t) FROM STDIN WITH (FORMAT csv)")
	require.NoError(t, err)
}
```

It can probably be simplified somewhat.

**Comment by jackc** [comment]
Thanks for the test case. I've managed to reproduce the issue and have pushed another fix.
