### ISSUE TITLE
help implementing CopyBoth

### ISSUE THREAD

**Issue by tcrayford** [jackc/pgconn#23]
Postgres has a `CopyBoth` protocol used in replication, which isn't exposed by this package (yet). I would like to contribute that, but I have some questions

- Would you accept such a contribution?
- What's a good way to test that? Postgres itself doesn't expose `CopyBoth` (as far as I can tell) except through the replication protocol, but relying on the replication protocol in tests does not feel like the best. I guess I can start up a replication connection, and a *non* replication connection and write into the non replication connection and check some bytes come down the wire?
- Does this function signature make sense to you?

```
// CopyBoth executes the copy command sql and copies all of r to the PostgreSQL server, writing results to w.
//
// Note: context cancellation will only interrupt operations on the underlying PostgreSQL network connection. Reads on r
// could still block.
func (pgConn *PgConn) CopyBoth(ctx context.Context, w io.Writer, r io.Reader, sql string) (CommandTag, error) {
```

I should be fine implementing this once I have an idea on how to actually test it, but that part seems tricky.

**Comment by jackc** [comment]
Have you seen https://github.com/jackc/pglogrepl ? That may already do what you want. If it doesn't, that would still probably be the best place for new replication features.

**Comment by tcrayford** [comment]
@jackc I had not! Thanks for the pointer! It looks like I can just work with the code there (I'm interested in physical rep, not logical), and adjust it to my needs. I think given that, it seems like `pgconn` doesn't need to implement `CopyBoth` :)
