### ISSUE TITLE
Missing conn.Begin

### ISSUE THREAD

**Issue by tzachshabtay** [jackc/pgconn#31]
I was trying to find how to start a transaction, from [this document](https://github.com/jackc/pgx/blob/251c1cb106d4fd169ffbd17840752fe0d451d978/doc.go) I should be doing `conn.Begin` but `pgconn` doesn't have a `Begin`?

**Comment by jackc** [comment]
That document is for `pgx`. `pgconn` is a lower level driver that `pgx` is built on top of.

`pgx` has a `Begin` method. `pgconn` does not.

In `pgconn`, you need to `Exec` the `begin;` and `commit;` SQL yourself.
