### ISSUE TITLE
Busy spinning the CPU (hardlock)

### ISSUE THREAD

**Issue by defigure** [jackc/pgconn#39]
I think there is a secondary bug here, but at least the first issue is:

https://github.com/jackc/pgconn/blob/2ccb66fe2159792f5b28d01e65e2461795a6f854/pgconn.go#L1154

The default: statement on a select means that it will not block (instead of the behaviour on blocking until either of the cases are satisfied). I can't see any reason for this since the loop doesn't do anything else, and this means currently while waiting it is doing nothing but spinning at full CPU.  This leaves a profile looking like:

```
+   43.85%  badpg   badpg-test        [.] runtime.selectgo                                                                                                                                
+   11.32%  badpg   badpg-test        [.] runtime.lock                                                                                                                                    
+   10.44%  badpg   badpg-test        [.] runtime.unlock                                                                                                                                  
+    5.69%  badpg   badpg-test        [.] runtime.selectrecv                                                                                                                              
+    5.40%  badpg   badpg-test        [.] runtime.sellock                                                                                                                                 
+    5.06%  badpg   badpg-test        [.] runtime.selunlock      
```

I don't see any reason not to remove the default clause.  The second bug is probably pg not noticing a connection termination somewhere, but I'm not sure yet where.

**Comment by jackc** [comment]
I can't see any reason for the empty default either. Removed.
