### ISSUE TITLE
Panic in parseDSNSettings caused by trailing backslash in connection string

### ISSUE THREAD

**Issue by eagraf** [jackc/pgconn#49]
An attempt at fuzz testing found a panic caused by a faulty connection string input such as `x=x\\` (backslash is escaped) which causes parseDSNSettings to panic. Because of this, attempts to call `pgconn.Connect` could cause unexpected crashes. The crash occurs [here](https://github.com/jackc/pgconn/blob/master/config.go#L511) due to an attempt to create a slice with an ending beyond the underlying capacity.

**Comment by jackc** [comment]
Thanks! Fixed.
