### ISSUE TITLE
Package looks for the wrong .pgpass location on Windows

### ISSUE THREAD

**Issue by kohenkatz** [jackc/pgconn#60]
While *nix systems have the `.pgpass` file in the user's home directory, on Windows the path to this file is `%APPDATA%\postgresql\pgpass.conf` (as noted in the [documentation](https://www.postgresql.org/docs/12/libpq-pgpass.html)).

(Weirdly, this does not seem to apply to `.pg_service.conf`, which remains in the home directory on Windows. 🤷)

Go makes it very easy to conditional-compile files based on operating system using build tags and magic filenames, so I would probably move `defaultSettings()` (and, once making changes, also `defaultHost()`) into their own file `defaults.go` with `// +build !windows` at the top, then add another file `defaults_windows.go` with the Windows versions of these functions.

I would be happy to submit a PR for this if you want.

**Comment by jackc** [comment]
Sounds good to me.

> (Weirdly, this does not seem to apply to .pg_service.conf, which remains in the home directory on Windows. 🤷)

My guess is this is due to the different file system permission structures of Windows and *nix. The `.pgpass` file needs to be secured.
