### ISSUE TITLE
ParseConfig seems to ignore options after empty option

### ISSUE THREAD

**Issue by alranel** [jackc/pgconn#62]
When supplying the following DSN to `ParseConfig()`:

```
host=localhost port=5433 user=postgres password= dbname=foo
```

the `dbname` option is ignored, and I get a connection to the default database (postgres) instead of the specified one.

If I change the order of the options like this:

```
dbname=foo host=localhost port=5433 user=postgres password=
```

I get the connection to the correct database.

I believe it may be caused by `password=` being empty, and breaking parsing of following options, but I'm not sure about this diagnosis.

**Comment by jackc** [comment]
PostgreSQL conn strings must have empty parameter quoted.

https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING

Here is what is happening in your first example: It is allowed for there to be space on either side of the `=`. So the conn string is being read as `password` is `dbname=foo`.

**Comment by alranel** [comment]
Thank you for explaning this behavior, now it's much more clear. This was not obvious to me since I never found an example with quoted parameters, so I would recommend to make it clear in the docs of this package in case others like me don't understand what's going on :)
