### ISSUE TITLE
Incorrect URI -connection implementation

### ISSUE THREAD

**Issue by otheus** [jackc/pgconn#69]
https://github.com/jackc/pgconn/blob/e4f3224f4c6d615b7199c9a606c4e3385efd1f21/pgconn.go#L238

Postgresql recognizes `dbname` not `database` as the parameter for the database instance to connect to.

**Comment by jackc** [comment]
See https://www.postgresql.org/docs/current/protocol-message-formats.html for the `StartupMessage`. Internally it **is** `database`.

**Comment by otheus** [comment]
Ah, I see. Well, something is printout the misleading error message, and I tracked it down to this. 
```
Connection failed: failed to connect to `host=/var/run/postgresql user=zabbix database=postgres`: dial error (dial unix /var/run/postg    resql/.    s.PGSQL.5432: connect: no such file or directory).
```

and
```
[Postgres] Connection failed: failed to connect to `host=/var/run/postgresql user=zabbix database=shouldignore`: server error (FATA    L: database "shouldignore" does not exist (SQLSTATE 3D000)).
```
These are invoked by a project called Zabbix, of which , zabbix agent 2 utilizes your libraries. I could not find the error message in their code. 

If I connect using a different method, ie, the `database` field is empty in the config-set (but seen in the connection string), I get the error with `dbname=....` instead.

```
Connection failed: failed to connect to `host=/var/run/postgresql user=zabbix database=postgres`: dial error (dial unix /var/run/postg    resql/.s.PGSQL.5432: connect: no such file or directory).`
```

**Comment by jackc** [comment]
For historical reasons the connection string allows `database` or `dbname` to set the database.

**Comment by andrejpodzimek** [comment]
Actually, it does **not** seem to allow `dbname`, which [has caused some confusion](https://github.com/timescale/promscale/issues/563#issuecomment-813083581) during my timescale/promscale experiments. (It does allow `database`, however, which looks non-standard, also based on [the PostgreSQL docs](https://www.postgresql.org/docs/current/libpq-connect.html).)

Specifically, this works (and should not):

```
postgres:///?database=db_promscale&user=pguser_promscale&password=<CENSORED>&host=/run/postgresql/&port=5432...
```

And this doesn’t work (and should):

```
postgres:///?dbname=db_promscale&user=pguser_promscale&password=<CENSORED>&host=/run/postgresql/&port=5432...
```

**Comment by jackc** [comment]
Huh, never occurred to me that someone would use `dbname` as a query parameter in a URL rather than put the database in the path portion. 

e.g. `postgres:///db_promscale?user=pguser_promscale&password=<CENSORED>&host=/run/postgresql/&port=5432...`

https://www.postgresql.org/docs/current/libpq-connect.html#id-1.7.3.8.3.6 doesn't give any examples of that.

Anyway, it was a simple enough fix.
