### ISSUE TITLE
Context expiration error should be returned instead of net error

### ISSUE THREAD

**Issue by jackc** [jackc/pgconn#80]
Context expiration is implemented by `SetDeadline` on the underlying `net.Conn`. This means that the error returned from a query can be the underlying net error instead of the context error. This is confusing for callers.

See https://github.com/jackc/pgx/issues/831.

**Comment by jackc** [comment]
I had the vague recollection that we used to do this. And sure enough back in `pgx/v3` it was done this way. 138254da5b02b80a548f7858f01636f9a426b918 removed `preferContextOverNetTimeoutError()` as part of the overall refactoring to Go 1.11 style errors and trying to minimize the number of error types and sentinel values. The thought was that `pgconn.Timeout` rendered it unnecessary. It looks like this part of the refactoring was incorrect. Presumably it should be fairly easy to restore.

**Comment by atombender** [comment]
Awesome. Thanks, @jackc.
