### ISSUE TITLE
Should context.Canceled really be a pgconn.Timeout error? 

### ISSUE THREAD

**Issue by jackc** [jackc/pgconn#81]
I initially did it this way because I saw a timeout error in the general sense of "we ran out of time to do the thing" regardless of why we ran out of time. For example, when running in an HTTP handler and the browser stops the request which cancels the context.

However in https://github.com/jackc/pgx/issues/831 @atombender and @adw1n both seemed to be against that. I am still kind of inclined to leave this alone, but if either of them or anyone else wants to make a case for that change I am open to it.

**Comment by atombender** [comment]
Just to summarize my argument, and add some new observations:

`pgconn.Timeout()` today returns `true` even for errors that don't specifically indicate a connection timeout. Aside from the fact that `context.Canceled` does not always indicate a timeout, it also tests for `net.Error`, which is a general-purpose Go error that is not guaranteed to come from pgconn itself.

This means that `pgconn.Timeout()`'s result is only reliable on errors returned directly by pgconn calls, and cannot be used higher up in the stack where you no longer know who produced it.

Regardless of the other problems, the question remains exactly what value `pgconn.Timeout()` provides to the developer. The lack of precision means it's more likely to be wrong than right, in my opinion. Intuitively, I would expect a function caled `pgconn.Timeout()` to only return true for Postgres timeouts and nothing else, but this is not the reality

**Comment by jackc** [comment]
I suppose there's also a `57014` error caused by `statement_timeout` on the server side. That is definitely a timeout error but is not caught by the existing `pgconn.Timeout()`.

There appear to be two root issues:

First, `pgconn.Timeout()` is too ambiguous and there is no way to discern between different kinds of timeouts. #80 would help.

Second, there is no way to distinguish an error that originated in pgconn from any other errors. Establishing a `pgconn.Error` interface that all errors returned from pgconn implement would be a possible solution.

If both of these were done then probably `pgconn.Timeout()` should be deprecated or at least its limitations documented.

**Comment by nelsam** [comment]
This caused us quite a stumble as well in the `WaitForNotification` logic.

We have code that listens on multiple channels, and it needs to periodically adjust the channels it's listening on.  `WaitForNotification` locks the connection, though, so we can't just call `conn.Exec("LISTEN foo")` or `conn.Exec("UNLISTEN foo")`.  Instead, we provide a cancel-able context to `WaitForNotification` and then have our code cancel the context before calling `LISTEN` or `UNLISTEN`.

In the code that calls `WaitForNotification`, we originally just checked for `errors.Is(err, context.Canceled)` - if the context was canceled, we knew we just needed to construct a new `context.Context` (with a new cancel function) and continue the loop, waiting for the next notification.  It took us some time to realize that the reason it wasn't working was that the error returned when we canceled the context was not wrapping `context.Canceled`.

Our code handles the timeout _now_, but we still have a case for `context.Canceled` because it feels like the error we're getting from `WaitForNotification` should be wrapping the `context.Canceled` error in that scenario.

**Comment by jackc** [comment]
So to make sure I understand, you are getting some sort of `net.Timeout` error instead of `context.Canceled` when canceling a `WaitForNotification`?

**Comment by nelsam** [comment]
Yes.  Here's a very rough stripped down (and probably not working) version of what our code looks like:

```
type notifier struct {
    conn *pgx.Conn
    
    notificationMu sync.Mutex
    notificationCancel func()
}

func (n *notifier) newNotificationCtx() context.Context {
    ctx, cancel := context.WithCancel(context.Background())
    n.notificationMu.Lock()
    defer n.notificationMu.Unlock()
    n.notificationCancel = cancel
    return ctx
}

func (n *notifier) Next() (*pgconn.Notification, error) {
    for {
        ctx := n.newNotificationCtx()
        notification, err :=  n.conn.WaitForNotification(ctx)
        if errors.Is(err, context.Canceled) {
            // this never occurs, currently
            continue
        }
        if timeouter, ok := err.(interface{ Timeout() bool }); ok && timeouter.Timeout() {
            // We have a large comment block here explaining that when the reader's context is canceled, the error
            // returned is from the net.Conn (due to how the context watcher works), so the timeout is _most likely_
            // from something that needs access to n.conn canceling the reader's context.
            continue
        }
        if err != nil {
            return nil, err
        }
        return notification, nil
    }
}

func (n *notifier) Listen(chanName string) error {
    n.notificationMu.Lock()
    defer n.notificationMu.Unlock()
    n.notificationCancel()
    _, err := n.conn.Exec(context.Background(), "LISTEN "+pgx.Identifier{chanName}.Sanitize())
    return err
}

// And some similar code for Unlisten
```

**Comment by jackc** [comment]
@nelsam  I think the current `pgconn.Timeout()` would actually work well in this situation. At least until when and if we narrow `pgconn.Timeout()` to not include `context.Canceled`.

But I do think that it would make sense for to return the context error instead of a `net.Error`. Probably this should be done everywhere but especially for `WaitForNotification`. This probably is a separate issue.

**Comment by jackc** [comment]
With #80 complete, I don't think it makes sense to change pgconn.Timeout(). Anyone who needs to handle context errors specifically now can.

@nelsam This means that as of 6996e8d6c546d45bab6f1e8b24c010f40f095e6e `WaitForNotification` should return the context error instead of a `net.Error` with `Timeout()`.
