### ISSUE TITLE
Add ability to PgConn.CopyTo to pass arguments

### ISSUE THREAD

**Issue by nkralles** [jackc/pgconn#83]
Currently when using the `PgConn.CopyTo` function you must supply the full sql as a `string`

```go 
var file *os.File
...
cmd, err = conn.PgConn().CopyTo(server.Context(), file, "COPY ( select * from tablexzy ) TO STDOUT WITH (FORMAT CSV, FORCE_QUOTE *)")
```
 
 When the `COPY` sql becomes very dynamic you are force to stringify the sql, ideally if `CopyTo` had the arguments parameter like `pgx.Conn` has it would make things a whole lot easier.  
 
 
 ```go 
var file *os.File
args := []interface{}{
	userId,
	groudIds
}
//column_1 text column and column_2 being an text array column
sql := `select * from tablexyz where $1 = column1 $2 && column_2`
...
cmd, err = conn.PgConn().CopyTo(server.Context(), file, fmt.Sprintf("COPY ( %s ) TO STDOUT WITH (FORMAT CSV, FORCE_QUOTE *)", sql),args...)
```

**Comment by jackc** [comment]
Unfortunately, this is not possible to do directly. pgconn uses the PostgreSQL extended query interface (i.e. prepared queries) to safely handle arguments for normal queries. But a `COPY` statement cannot be prepared. And as pgconn doesn't have any Go to/from PostgreSQL type handling / conversion, it couldn't be done here. It *may* be possible at the pgx level using the simple protocol path to sanitize the query, but that path is a bit tricky and I don't really want to encourage its use.
