### ISSUE TITLE
Support for PG14 target_session_attrs values

### ISSUE THREAD

**Issue by phemmer** [jackc/pgconn#89]
PG14 adds several new values for the `target_session_attrs` connection parameter. These obviously have use since libpq implements them, but in my use case, I was looking for a `read-only` setting so that I could have clients which only need to query the DB use the replica(s), and save hardware resources on the master for data ingestion.

Yes, PG14 isn't out yet, but since this is a client-side feature, doesn't require any new support from the server, and is backwards compatible, it could be implemented now.

The new values are:

* `read-only`  
session must not accept read-write transactions by default (the converse)

* `primary`  
server must not be in hot standby mode

* `standby`  
server must be in hot standby mode

* `prefer-standby`  
first try to find a standby server, but if none of the listed hosts is a standby server, try again in any mode

https://www.postgresql.org/docs/14/libpq-connect.html

**Comment by jackc** [comment]
Seems reasonable to me. But not sure if / when I would have a chance to look at it.

**Comment by 0sc** [comment]
I'd like to work on this if no one is working on it yet.

**Comment by jackc** [comment]
I don't know of anyone working on it. You're welcome to it. 👍

**Comment by jackc** [comment]
Merged in PR #101.
