### ISSUE TITLE
Hijack and Construct

### ISSUE THREAD

**Issue by jackc** [jackc/pgconn#9]
It would be interesting to have a `Hijack` method that took control of the underlying `net.Conn` from the `PgConn`. This would let `pgconn` be used to connect to the PostgreSQL server and have something else take over the actual connection.

The reciprocal function would be `Construct` which would take an already connected `net.Conn` and any other requirements and built a `*PgConn`.

Not sure of the actual utility but it seems like it would make pgconn much more composable with other projects.

**Comment by jackc** [comment]
`Construct` and `Deconstruct` might be better names. That would make clearer the inverse nature of the operations.

**Comment by sveniu** [comment]
I'm in the early stages of making a postgres load balancer (think pgbouncer), and was looking for a way to utilize pgconn for the proxy-to-server connection to simplify the upstream connection, while the client-to-proxy connection happens via a pgproto3 Backend.

Related to hijacking the net.Conn, it seems to make sense to hijack the frontend from PgConn in my case. I guess it would also work to get the net.Conn and then constructing a new pgproto3.Frontend using NewFrontend.

Either way, I'm interested in this kind of composability. I'm also open to ideas of alternative approaches.

**Comment by jackc** [comment]
Just added a `Hijack` method to `PgConn`. It returns all the internal data necessary to use a connected PostgreSQL connection. The returned `HijackedConn` struct should give you everything you need. The `Construct` function can be used to perform the inverse operation.

Since these functions expose internal implementation details I've marked these functions as out of scope for semantic version compatibility guarantees, but I don't actually expect them to change.
