### ISSUE TITLE
Cursor processing pattern

### ISSUE THREAD

**Issue by DarcInc** [jackc/pgconn#90]
After some trial and error, this is what I've come up with but wanted to get your opinion.  My initial naive implementation used a plain select and that locked the connection until all the results were read.  Meaning, I couldn't execute other statements until the reader was closed.  Use Exec to open a cursor, Query/QueryRow to fetch rows from the cursor, and then Exec to close the cursor, when done.  

```sql
DECLARE dup_hash_crsr CURSOR FOR SELECT file_hash, count(*) AS image_count 
		FROM all_files 
		GROUP BY file_hash 
		HAVING count(*) > 1
```

- Execute `FETCH 1 FROM dup_hash_crsr` and read in all the rows from that fetch.  Could be fetch 1, 10, 30 or whatever makes sense for the application.
- At this point the connection should be unlocked so I could execute other statements.  
- Loop back to fetch.

Use `CLOSE dup_hash_crsr` to close the cursor.

**Comment by jackc** [comment]
I've never used cursors in production, but what you describe sounds reasonable if you need to use them. But AFAIK cursors aren't used much nowadays.

**Comment by DarcInc** [comment]
It's okay.  I can use them.  I'm an old.
