### ISSUE TITLE
`PgConn.Close()` sometimes hangs even though the context has been canceled

### ISSUE THREAD

**Issue by ovandriyanov** [jackc/pgconn#94]
I believe there is a race condition between `Close()` and `ReceiveMessage()`, but I can reproduce it reliably only after adding a delay into `ContextWatcher.Unwatch()`.

Steps to reproduce:
1. Patch pgconn sources:
```diff
diff --git a/internal/ctxwatch/context_watcher.go b/internal/ctxwatch/context_watcher.go
--- a/internal/ctxwatch/context_watcher.go
+++ b/internal/ctxwatch/context_watcher.go
@@ -2,6 +2,7 @@ package ctxwatch
 
 import (
 	"context"
+	"time"
 )
 
 // ContextWatcher watches a context and performs an action when the context is canceled. It can watch one context at a
@@ -55,6 +56,7 @@ func (cw *ContextWatcher) Watch(ctx context.Context) {
 // called then onUnwatchAfterCancel will also be called.
 func (cw *ContextWatcher) Unwatch() {
 	if cw.watchInProgress {
+		time.Sleep(time.Second)
 		cw.unwatchChan <- struct{}{}
 		if cw.onCancelWasCalled {
 			cw.onUnwatchAfterCancel()
```
2. Ensure PostgreSQL server is reachable at `host=::1 port=6001 dbname=postgres user=postgres password=123`
3. Run the following program:
```go
package main

import (
	"context"
	"sync"
	"time"

	"github.com/jackc/pgconn"
)

func noerror(err error) {
	if err != nil {
		panic(err)
	}
}

func main() {
	pgc, err := pgconn.Connect(context.Background(), "host=::1 port=6001 dbname=postgres user=postgres password=123")
	noerror(err)

	ctx, cancel := context.WithCancel(context.Background())
	var wg sync.WaitGroup
	wg.Add(1)
	go func() {
		defer wg.Done()
		pgc.ReceiveMessage(ctx)
	}()
	time.Sleep(100 * time.Millisecond)
	cancel()

	closeCtx, cancelClose := context.WithTimeout(context.Background(), 200*time.Millisecond)
	pgc.Close(closeCtx)
	cancelClose()

	wg.Wait()
}
```
The program is supposed to exit after about one second but instead it hangs forever.

I tried to debug it a little bit and it seems like there is a deadlock in the `ContextWatcher.Unwatch()`: it tries to send a message to a channel which is not being read from anymore, since two calls to `Unwatch()` took place concurrently and the one from `ReceiveMessage` won the race.

The deadlock with the same symptoms happens once in a while in my tests, but of course there aren't any synthetic delays in the  pgconn code.

**Comment by jackc** [comment]
Thanks for the detailed bug report. I was able to construct a test that triggered the race detector and fix the underlying issue.
