### ISSUE TITLE
Support LookupFunc returning a host and port

### ISSUE THREAD

**Issue by jameshartig** [jackc/pgconn#97]
Currently if `LookupFunc` returns a `host:port` then it ends up getting wrapped again with the original port from the url. We override `LookupFunc` so we can do our own SRV lookups against Consul and we don't guarantee that every instance will be on the same port. I think all that's needed is that `expandWithIPs` needs to do a `net.SplitHostPort` to see if a port was returned and use that instead. I can make a PR for it but I thought I'd make sure you're okay with it first.

**Comment by jackc** [comment]
I haven't worked in that type of environment so I don't know if there is any other config that is/should be pulled from service discovery. If there is, then maybe a more general service discovery callback function is in order.

If not, then the change you suggest to `expandWithIPs` is fine.

**Comment by jameshartig** [comment]
@jackc I think there's too much variety in the actual service discovery options to add something like that and I don't feel comfortable designing an API. I think in the future, adding a way to pass all of the fallback configs to Connect instead of building them based off the lookup could be an option.

I opened https://github.com/jackc/pgconn/pull/99 with the small change to `expandWithIPs` and added a test as well
